Rework `no_std` API and enable `std` by default
- Extract `Reportable` and other surrogate types/impls
  into `surrogate_error_trait` module
- Extract surrogate type aliases from `prelude`
  into `surrogate_error_trait::prelude` module
- Enable the `std` feature by default
- Fix and clarify several parts of the documentation

This change avoids conflicts between `std` and `no_std` users:
The old implementation of the `std` feature in `lazy_errors`
violated cargo's “features should be additive” rule.
When one of the user's dependencies depended on `lazy_errors` with
`std` support, and another one depended on `lazy_errors` having
`std` disabled, the dependencies may have failed to compile.

When `core::error::Error` reaches stable, depending on the standard lib
won't be necessary anymore for `lazy_errors`. If the user's dependencies
switch from `std`-disabled to `std`-enabled `lazy_errors` usage
at a different pace (this is a breaking change after all),
this situation may increase changes to trigger aforementioned
compilation errors. So better break the API now, explicitly,
than having unexpected compilation errors in a few weeks/months.

When `core::error::Error` is stable, the `std` feature
will be removed and a `error_in_core` feature will be added.
For people using `std` implicitly (via default features),
nothing will change, except that they magically don't
depend on the standard library anymore.
People using `#![no_std]` can start using the “real” types or
continue using the surrogate error trait by disabling `error_in_core`
to support old Rust versions.